//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perseus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HKNewsPaper
    {
        public HKNewsPaper()
        {
            this.HKNewsItem = new HashSet<HKNewsItem>();
        }
    
        public int MailId { get; set; }
        public string Sender { get; set; }
        public Nullable<System.DateTime> Sent { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string RPublisher { get; set; }
        public string REditor { get; set; }
        public string Title { get; set; }
        public bool IsDraft { get; set; }
    
        public virtual ICollection<HKNewsItem> HKNewsItem { get; set; }
        public virtual User User { get; set; }
    }
}
