//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perseus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.Children = new HashSet<MenuItem>();
        }
    
        public int Id { get; set; }
        public int MenuId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string LinkPath { get; set; }
        public string LinkTitle { get; set; }
        public Nullable<int> Permission_PermissionId { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<MenuItem> Children { get; set; }
        public virtual MenuItem Parent { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
