//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perseus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Permission = new HashSet<Permission>();
            this.Setting = new HashSet<Setting>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
    
        public virtual ICollection<Permission> Permission { get; set; }
        public virtual ICollection<Setting> Setting { get; set; }
    }
}
